/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.Charac;

/**
 *
 * @author sinsentido
 */
public class CharSheet extends javax.swing.JDialog {

    /**
     * Creates new form CharSheet
     */
    public CharSheet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void printCharacValues(Charac charac){
        //Character basic information
        valueCharacterName.setText(charac.getCharName());
        valuePlayer.setText(charac.getPlayer());
        valueChronicle.setText(charac.getChronicle());
        valueNature.setText(charac.getNature());
        valueDemeanor.setText(charac.getDemeanor());
        valueConcept.setText(charac.getConcept());
        valueClan.setText(charac.getClan());
        valueGeneration.setText(charac.getGeneration());
        valueSire.setText(charac.getSire());
        
        //Character attributes
        valueStrength.setText(Byte.toString(charac.getStrength()));
        valueDexterity.setText(Byte.toString(charac.getDexterity()));
        valueStamina.setText(Byte.toString(charac.getStamina()));
        valueCharisma.setText(Byte.toString(charac.getCharisma()));
        valueManipulation.setText(Byte.toString(charac.getManipulation()));
        valueAppearence.setText(Byte.toString(charac.getAppearence()));
        valuePerception.setText(Byte.toString(charac.getPerception()));
        valueIntelligence.setText(Byte.toString(charac.getIntelligence()));
        valueWits.setText(Byte.toString(charac.getWits()));
        
        //Character history
        valueHistory.setText(charac.getHistory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueHistory = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        panelBasicInformation = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCharacterName = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblChronic = new javax.swing.JLabel();
        valueCharacterName = new javax.swing.JLabel();
        valuePlayer = new javax.swing.JLabel();
        valueChronicle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNature = new javax.swing.JLabel();
        lblDemeanor = new javax.swing.JLabel();
        lblConcept = new javax.swing.JLabel();
        valueNature = new javax.swing.JLabel();
        valueDemeanor = new javax.swing.JLabel();
        valueConcept = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblGeneration = new javax.swing.JLabel();
        lblSire = new javax.swing.JLabel();
        lblClan = new javax.swing.JLabel();
        valueClan = new javax.swing.JLabel();
        valueGeneration = new javax.swing.JLabel();
        valueSire = new javax.swing.JLabel();
        lblAttributes = new javax.swing.JLabel();
        panelAttributes1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblPhysical1 = new javax.swing.JLabel();
        lblStrength1 = new javax.swing.JLabel();
        lblDexterity1 = new javax.swing.JLabel();
        lblStamina1 = new javax.swing.JLabel();
        valueDexterity = new javax.swing.JLabel();
        valueStrength = new javax.swing.JLabel();
        valueStamina = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblSocial = new javax.swing.JLabel();
        lblCharisma = new javax.swing.JLabel();
        lblManipulation = new javax.swing.JLabel();
        lblAppearence = new javax.swing.JLabel();
        valueCharisma = new javax.swing.JLabel();
        valueManipulation = new javax.swing.JLabel();
        valueAppearence = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblMental = new javax.swing.JLabel();
        lblPerception = new javax.swing.JLabel();
        lblIntelligence = new javax.swing.JLabel();
        lblWits = new javax.swing.JLabel();
        valuePerception = new javax.swing.JLabel();
        valueIntelligence = new javax.swing.JLabel();
        valueWits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblHistory.setFont(new java.awt.Font("Z003", 3, 24)); // NOI18N
        lblHistory.setForeground(new java.awt.Color(180, 0, 0));
        lblHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistory.setText("Character history");

        valueHistory.setBackground(new java.awt.Color(204, 204, 204));
        valueHistory.setColumns(20);
        valueHistory.setLineWrap(true);
        valueHistory.setRows(5);
        valueHistory.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(valueHistory);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Z003", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(180, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vampyre The Masquerade");

        panelBasicInformation.setLayout(new java.awt.GridLayout(1, 3));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblCharacterName.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblCharacterName.setForeground(new java.awt.Color(0, 0, 0));
        lblCharacterName.setText("Character:");

        lblPlayer.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblPlayer.setForeground(new java.awt.Color(0, 0, 0));
        lblPlayer.setText("Player:");

        lblChronic.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblChronic.setForeground(new java.awt.Color(0, 0, 0));
        lblChronic.setText("Chronicle:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChronic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueChronicle, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(valuePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valuePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChronic)
                    .addComponent(valueChronicle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblNature.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblNature.setForeground(new java.awt.Color(0, 0, 0));
        lblNature.setText("Nature:");

        lblDemeanor.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblDemeanor.setForeground(new java.awt.Color(0, 0, 0));
        lblDemeanor.setText("Demeanor:");

        lblConcept.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblConcept.setForeground(new java.awt.Color(0, 0, 0));
        lblConcept.setText("Concept");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblConcept, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(valueConcept, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNature, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(valueNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDemeanor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblGeneration.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblGeneration.setForeground(new java.awt.Color(0, 0, 0));
        lblGeneration.setText("Generation:");

        lblSire.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblSire.setForeground(new java.awt.Color(0, 0, 0));
        lblSire.setText("Sire:");

        lblClan.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblClan.setForeground(new java.awt.Color(0, 0, 0));
        lblClan.setText("Clan:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneration)
                    .addComponent(lblSire)
                    .addComponent(lblClan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueClan, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(valueGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueSire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSire)
                    .addComponent(valueSire, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel4);

        lblAttributes.setFont(new java.awt.Font("Z003", 3, 24)); // NOI18N
        lblAttributes.setForeground(new java.awt.Color(180, 0, 0));
        lblAttributes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttributes.setText("Attributes");

        panelAttributes1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblPhysical1.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        lblPhysical1.setForeground(new java.awt.Color(180, 0, 0));
        lblPhysical1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhysical1.setText("Physical");

        lblStrength1.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblStrength1.setForeground(new java.awt.Color(0, 0, 0));
        lblStrength1.setText("Strength _________");

        lblDexterity1.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblDexterity1.setForeground(new java.awt.Color(0, 0, 0));
        lblDexterity1.setText("Dexterity ________");

        lblStamina1.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblStamina1.setForeground(new java.awt.Color(0, 0, 0));
        lblStamina1.setText("Stamina _________");

        valueDexterity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueStrength.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueStamina.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblStrength1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueStrength))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDexterity1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueDexterity))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblStamina1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueStamina)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhysical1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblPhysical1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrength1)
                    .addComponent(valueStrength))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDexterity1)
                    .addComponent(valueDexterity))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStamina1)
                    .addComponent(valueStamina))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblSocial.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        lblSocial.setForeground(new java.awt.Color(180, 0, 0));
        lblSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocial.setText("Social");

        lblCharisma.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblCharisma.setForeground(new java.awt.Color(0, 0, 0));
        lblCharisma.setText("Charisma ________");

        lblManipulation.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblManipulation.setForeground(new java.awt.Color(0, 0, 0));
        lblManipulation.setText("Manipulation ____");

        lblAppearence.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblAppearence.setForeground(new java.awt.Color(0, 0, 0));
        lblAppearence.setText("Appearence ______");

        valueCharisma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueManipulation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueAppearence.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblCharisma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueCharisma))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblManipulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueManipulation))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblAppearence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueAppearence)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharisma)
                    .addComponent(valueCharisma))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManipulation)
                    .addComponent(valueManipulation))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppearence)
                    .addComponent(valueAppearence))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblMental.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        lblMental.setForeground(new java.awt.Color(180, 0, 0));
        lblMental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMental.setText("Mental");

        lblPerception.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblPerception.setForeground(new java.awt.Color(0, 0, 0));
        lblPerception.setText("Perception _______");

        lblIntelligence.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblIntelligence.setForeground(new java.awt.Color(0, 0, 0));
        lblIntelligence.setText("Intelligence ______");

        lblWits.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        lblWits.setForeground(new java.awt.Color(0, 0, 0));
        lblWits.setText("Wits ___________");

        valuePerception.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueIntelligence.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueWits.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMental, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblPerception)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valuePerception))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblIntelligence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueIntelligence))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblWits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueWits)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lblMental, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerception)
                    .addComponent(valuePerception))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntelligence)
                    .addComponent(valueIntelligence))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWits)
                    .addComponent(valueWits))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 156, Short.MAX_VALUE)
                    .addComponent(panelBasicInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAttributes1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(lblAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(lblHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(panelBasicInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(panelAttributes1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppearence;
    private javax.swing.JLabel lblAttributes;
    private javax.swing.JLabel lblCharacterName;
    private javax.swing.JLabel lblCharisma;
    private javax.swing.JLabel lblChronic;
    private javax.swing.JLabel lblClan;
    private javax.swing.JLabel lblConcept;
    private javax.swing.JLabel lblDemeanor;
    private javax.swing.JLabel lblDexterity1;
    private javax.swing.JLabel lblGeneration;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblIntelligence;
    private javax.swing.JLabel lblManipulation;
    private javax.swing.JLabel lblMental;
    private javax.swing.JLabel lblNature;
    private javax.swing.JLabel lblPerception;
    private javax.swing.JLabel lblPhysical1;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblSire;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblStamina1;
    private javax.swing.JLabel lblStrength1;
    private javax.swing.JLabel lblWits;
    private javax.swing.JPanel panelAttributes1;
    private javax.swing.JPanel panelBasicInformation;
    private javax.swing.JLabel valueAppearence;
    private javax.swing.JLabel valueCharacterName;
    private javax.swing.JLabel valueCharisma;
    private javax.swing.JLabel valueChronicle;
    private javax.swing.JLabel valueClan;
    private javax.swing.JLabel valueConcept;
    private javax.swing.JLabel valueDemeanor;
    private javax.swing.JLabel valueDexterity;
    private javax.swing.JLabel valueGeneration;
    private javax.swing.JTextArea valueHistory;
    private javax.swing.JLabel valueIntelligence;
    private javax.swing.JLabel valueManipulation;
    private javax.swing.JLabel valueNature;
    private javax.swing.JLabel valuePerception;
    private javax.swing.JLabel valuePlayer;
    private javax.swing.JLabel valueSire;
    private javax.swing.JLabel valueStamina;
    private javax.swing.JLabel valueStrength;
    private javax.swing.JLabel valueWits;
    // End of variables declaration//GEN-END:variables
}
