/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.Charac;

/**
 *
 * @author sinsentido
 */
public class CharSheet extends javax.swing.JDialog {

    /**
     * Creates new form CharSheet
     */
    public CharSheet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void printCharacValues(Charac charac){
        //Character basic information
        valueCharacterName.setText(charac.getCharName());
        valuePlayer.setText(charac.getPlayer());
        valueChronicle.setText(charac.getChronicle());
        valueNature.setText(charac.getNature());
        valueDemeanor.setText(charac.getDemeanor());
        valueConcept.setText(charac.getConcept());
        valueClan.setText(charac.getClan());
        valueGeneration.setText(charac.getGeneration());
        valueSire.setText(charac.getSire());
        
        //Character attributes
        valueStrength.setText(Byte.toString(charac.getStrength()));
        valueDexterity.setText(Byte.toString(charac.getDexterity()));
        valueStamina.setText(Byte.toString(charac.getStamina()));
        valueCharisma.setText(Byte.toString(charac.getCharisma()));
        valueManipulation.setText(Byte.toString(charac.getManipulation()));
        valueAppearence.setText(Byte.toString(charac.getAppearence()));
        valuePerception.setText(Byte.toString(charac.getPerception()));
        valueIntelligence.setText(Byte.toString(charac.getIntelligence()));
        valueWits.setText(Byte.toString(charac.getWits()));
        
        //Character history
        valueHistory.setText(charac.getHistory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        panelBasicInformation = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCharacterName = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblChronic = new javax.swing.JLabel();
        valueCharacterName = new javax.swing.JLabel();
        valuePlayer = new javax.swing.JLabel();
        valueChronicle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNature = new javax.swing.JLabel();
        lblDemeanor = new javax.swing.JLabel();
        lblConcept = new javax.swing.JLabel();
        valueNature = new javax.swing.JLabel();
        valueDemeanor = new javax.swing.JLabel();
        valueConcept = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblGeneration = new javax.swing.JLabel();
        lblSire = new javax.swing.JLabel();
        lblClan = new javax.swing.JLabel();
        valueClan = new javax.swing.JLabel();
        valueGeneration = new javax.swing.JLabel();
        valueSire = new javax.swing.JLabel();
        lblAttributes = new javax.swing.JLabel();
        panelAttributes1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblPhysical1 = new javax.swing.JLabel();
        lblStrength1 = new javax.swing.JLabel();
        lblDexterity1 = new javax.swing.JLabel();
        lblStamina1 = new javax.swing.JLabel();
        valueDexterity = new javax.swing.JLabel();
        valueStrength = new javax.swing.JLabel();
        valueStamina = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblSocial = new javax.swing.JLabel();
        lblCharisma = new javax.swing.JLabel();
        lblManipulation = new javax.swing.JLabel();
        lblAppearence = new javax.swing.JLabel();
        valueCharisma = new javax.swing.JLabel();
        valueManipulation = new javax.swing.JLabel();
        valueAppearence = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblMental = new javax.swing.JLabel();
        lblPerception = new javax.swing.JLabel();
        lblIntelligence = new javax.swing.JLabel();
        lblWits = new javax.swing.JLabel();
        valuePerception = new javax.swing.JLabel();
        valueIntelligence = new javax.swing.JLabel();
        valueWits = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueHistory = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vampyre The Masquerade");

        panelBasicInformation.setLayout(new java.awt.GridLayout(1, 3));

        lblCharacterName.setText("Character:");

        lblPlayer.setText("Player:");

        lblChronic.setText("Chronicle:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChronic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueChronicle, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(valuePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valuePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChronic)
                    .addComponent(valueChronicle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel2);

        lblNature.setText("Nature:");

        lblDemeanor.setText("Demeanor:");

        lblConcept.setText("Concept");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblConcept, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(valueConcept, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNature, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(valueNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDemeanor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel3);

        lblGeneration.setText("Generation:");

        lblSire.setText("Sire:");

        lblClan.setText("Clan:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneration)
                    .addComponent(lblSire)
                    .addComponent(lblClan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueClan, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(valueGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueSire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSire)
                    .addComponent(valueSire, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelBasicInformation.add(jPanel4);

        lblAttributes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAttributes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttributes.setText("Attributes");

        panelAttributes1.setLayout(new java.awt.GridLayout(1, 3));

        lblPhysical1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPhysical1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhysical1.setText("Physical");

        lblStrength1.setText("Strength ____________");

        lblDexterity1.setText("Dexterity ____________");

        lblStamina1.setText("Stamina _____________");

        valueDexterity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueStrength.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueStamina.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhysical1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblStrength1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueStrength))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDexterity1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueDexterity))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblStamina1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueStamina)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblPhysical1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrength1)
                    .addComponent(valueStrength))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDexterity1)
                    .addComponent(valueDexterity))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStamina1)
                    .addComponent(valueStamina))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel6);

        lblSocial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocial.setText("Social");

        lblCharisma.setText("Charisma _______________");

        lblManipulation.setText("Manipulation ___________");

        lblAppearence.setText("Appearence ____________");

        valueCharisma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueManipulation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueAppearence.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblCharisma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueCharisma))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblManipulation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueManipulation))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblAppearence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueAppearence)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharisma)
                    .addComponent(valueCharisma))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManipulation)
                    .addComponent(valueManipulation))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppearence)
                    .addComponent(valueAppearence))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel7);

        lblMental.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMental.setText("Mental");

        lblPerception.setText("Perception _____________");

        lblIntelligence.setText("Intelligence ____________");

        lblWits.setText("Wits ___________________");

        valuePerception.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueIntelligence.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        valueWits.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMental, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblPerception)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valuePerception))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblIntelligence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueIntelligence))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblWits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueWits)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lblMental, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerception)
                    .addComponent(valuePerception))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntelligence)
                    .addComponent(valueIntelligence))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWits)
                    .addComponent(valueWits))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        panelAttributes1.add(jPanel8);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Character history");

        valueHistory.setColumns(20);
        valueHistory.setLineWrap(true);
        valueHistory.setRows(5);
        jScrollPane1.setViewportView(valueHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAttributes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBasicInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAttributes1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(lblAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(panelBasicInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(518, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(panelAttributes1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppearence;
    private javax.swing.JLabel lblAttributes;
    private javax.swing.JLabel lblCharacterName;
    private javax.swing.JLabel lblCharisma;
    private javax.swing.JLabel lblChronic;
    private javax.swing.JLabel lblClan;
    private javax.swing.JLabel lblConcept;
    private javax.swing.JLabel lblDemeanor;
    private javax.swing.JLabel lblDexterity1;
    private javax.swing.JLabel lblGeneration;
    private javax.swing.JLabel lblIntelligence;
    private javax.swing.JLabel lblManipulation;
    private javax.swing.JLabel lblMental;
    private javax.swing.JLabel lblNature;
    private javax.swing.JLabel lblPerception;
    private javax.swing.JLabel lblPhysical1;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblSire;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblStamina1;
    private javax.swing.JLabel lblStrength1;
    private javax.swing.JLabel lblWits;
    private javax.swing.JPanel panelAttributes1;
    private javax.swing.JPanel panelBasicInformation;
    private javax.swing.JLabel valueAppearence;
    private javax.swing.JLabel valueCharacterName;
    private javax.swing.JLabel valueCharisma;
    private javax.swing.JLabel valueChronicle;
    private javax.swing.JLabel valueClan;
    private javax.swing.JLabel valueConcept;
    private javax.swing.JLabel valueDemeanor;
    private javax.swing.JLabel valueDexterity;
    private javax.swing.JLabel valueGeneration;
    private javax.swing.JTextArea valueHistory;
    private javax.swing.JLabel valueIntelligence;
    private javax.swing.JLabel valueManipulation;
    private javax.swing.JLabel valueNature;
    private javax.swing.JLabel valuePerception;
    private javax.swing.JLabel valuePlayer;
    private javax.swing.JLabel valueSire;
    private javax.swing.JLabel valueStamina;
    private javax.swing.JLabel valueStrength;
    private javax.swing.JLabel valueWits;
    // End of variables declaration//GEN-END:variables
}
