/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.Charac;
import javax.swing.JOptionPane;

/**
 *
 * @author sinsentido
 */
public class CreateCharacter1 extends javax.swing.JDialog {
    private MainScreen mainScreen;

    /**
     * Creates new form CreateCharacter1
     */
    public CreateCharacter1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mainScreen = (MainScreen)parent;
    }
    
    public Charac getDataPart1(){
                
        return new Charac(txtAddCharacterName.getText().toString(), txtAddPlayerName.getText().toString(),
                txtAddChronicle.getText().toString(), txtAddNature.getItemAt(txtAddNature.getSelectedIndex()),
                txtAddDemeanor.getItemAt(txtAddDemeanor.getSelectedIndex()), txtAddConcept.getItemAt(txtAddConcept.getSelectedIndex()),
                txtAddClan.getItemAt(txtAddClan.getSelectedIndex()), txtAddGeneration.getText().toString(),
                txtAddSire.getText().toString());
    }
    
    private boolean areFieldsRight(){
        if(txtAddCharacterName.getText().isEmpty() || txtAddPlayerName.getText().isEmpty() || txtAddChronicle.getText().isEmpty()
                || txtAddGeneration.getText().isEmpty() || txtAddSire.getText().isEmpty()){
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitleAddCharacter1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAddCharacterName = new javax.swing.JLabel();
        lblAddPlayerName = new javax.swing.JLabel();
        lblAddChronicle = new javax.swing.JLabel();
        txtAddCharacterName = new javax.swing.JTextField();
        txtAddPlayerName = new javax.swing.JTextField();
        txtAddChronicle = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblAddNature = new javax.swing.JLabel();
        lblAddDemeanor = new javax.swing.JLabel();
        lblAddConcept = new javax.swing.JLabel();
        txtAddNature = new javax.swing.JComboBox<>();
        txtAddDemeanor = new javax.swing.JComboBox<>();
        txtAddConcept = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblAddClan = new javax.swing.JLabel();
        lblAddGeneration = new javax.swing.JLabel();
        lblAddSire = new javax.swing.JLabel();
        txtAddClan = new javax.swing.JComboBox<>();
        txtAddGeneration = new javax.swing.JTextField();
        txtAddSire = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitleAddCharacter1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitleAddCharacter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAddCharacter1.setText("Creating character step 1/3");

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        lblAddCharacterName.setText("Character name");

        lblAddPlayerName.setText("Player name");

        lblAddChronicle.setText("Chronicle");

        txtAddCharacterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCharacterNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddCharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddChronicle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddCharacterName)
                    .addComponent(txtAddPlayerName)
                    .addComponent(txtAddChronicle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCharacterName)
                    .addComponent(txtAddCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddPlayerName)
                    .addComponent(txtAddPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddChronicle)
                    .addComponent(txtAddChronicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        lblAddNature.setText("Nature");

        lblAddDemeanor.setText("Demeanor");

        lblAddConcept.setText("Concept");

        txtAddNature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architect", "Autocrat", "Autist", "Avant-Garde", "Bon Vivant", "Bravo", "Caregiver", "Celebrant", "Cavalier", "Child", "Competitor", "Confidant", "Critic", "Curmudgeon", "Dabbler", "Deviant", "Director", "Fanatic", "Gallant", "Honest", "Idealist", "Jobsworth", "Judge", "Loner", "Manipulator", "Martyr", "Masochist", "Mediator", "Monster", "Optimist", "Pedagogue", "Penitent", "Perfectionist", "Plotter" }));

        txtAddDemeanor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architect", "Autocrat", "Autist", "Avant-Garde", "Bon Vivant", "Bravo", "Caregiver", "Celebrant", "Cavalier", "Child", "Competitor", "Confidant", "Critic", "Curmudgeon", "Dabbler", "Deviant", "Director", "Fanatic", "Gallant", "Honest", "Idealist", "Jobsworth", "Judge", "Loner", "Manipulator", "Martyr", "Masochist", "Mediator", "Monster", "Optimist", "Pedagogue", "Penitent", "Perfectionist", "Plotter" }));

        txtAddConcept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criminal", "Dilettante", "Drifter", "Entertainer", "Intellectual", "Investigator", "Kid", "Nighlifter", "Outsider", "Politician", "Professional", "Punk", "Reporter", "Socialite", "Soldier", "Worker" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddDemeanor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddNature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddNature, 0, 200, Short.MAX_VALUE)
                    .addComponent(txtAddDemeanor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddConcept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddNature)
                    .addComponent(txtAddNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddDemeanor)
                    .addComponent(txtAddDemeanor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddConcept)
                    .addComponent(txtAddConcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        lblAddClan.setText("Clan");

        lblAddGeneration.setText("Generation");

        lblAddSire.setText("Sire");

        txtAddClan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assamite", "Brujah", "Followers of Set", "Gangrel", "Giovanni", "Lasombra", "Malkavian", "Nosferatu", "Ravnos", "Toreador", "Tremere", "Tzimisce", "Ventrue", "No Clan" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddGeneration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddSire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddClan, 0, 200, Short.MAX_VALUE)
                    .addComponent(txtAddGeneration)
                    .addComponent(txtAddSire))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddClan)
                    .addComponent(txtAddClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddGeneration)
                    .addComponent(txtAddGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddSire)
                    .addComponent(txtAddSire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitleAddCharacter1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitleAddCharacter1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddCharacterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCharacterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCharacterNameActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        CreateCharacter2 createCharacter2 = new CreateCharacter2(mainScreen, true);
        
        if(areFieldsRight()){
            createCharacter2.getData1(getDataPart1());
            createCharacter2.setVisible(true);       
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Can not be empty fields.", 
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAddCharacterName;
    private javax.swing.JLabel lblAddChronicle;
    private javax.swing.JLabel lblAddClan;
    private javax.swing.JLabel lblAddConcept;
    private javax.swing.JLabel lblAddDemeanor;
    private javax.swing.JLabel lblAddGeneration;
    private javax.swing.JLabel lblAddNature;
    private javax.swing.JLabel lblAddPlayerName;
    private javax.swing.JLabel lblAddSire;
    private javax.swing.JLabel lblTitleAddCharacter1;
    private javax.swing.JTextField txtAddCharacterName;
    private javax.swing.JTextField txtAddChronicle;
    private javax.swing.JComboBox<String> txtAddClan;
    private javax.swing.JComboBox<String> txtAddConcept;
    private javax.swing.JComboBox<String> txtAddDemeanor;
    private javax.swing.JTextField txtAddGeneration;
    private javax.swing.JComboBox<String> txtAddNature;
    private javax.swing.JTextField txtAddPlayerName;
    private javax.swing.JTextField txtAddSire;
    // End of variables declaration//GEN-END:variables
}
