/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.Charac;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import logic.Logic;

/**
 *
 * @author sinsentido
 */
public class MainScreen extends javax.swing.JFrame {
    public String[] data1 = new String[9];
    public Byte[] data2 = new Byte[9];
    public String data3 = null;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        loadBackgroundImage();
        Logic.createSaveFolder();
    }

    private void loadBackgroundImage(){
        File backgroundImageFile = new File("./vampWallpaper.jpg");
        
        if(!backgroundImageFile.exists()){
            System.out.println("Image doesn't exist");
        }
        else{
            backgroundImage.setIcon(new javax.swing.ImageIcon(backgroundImageFile.getAbsolutePath())); // NOI18N
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNewCharacter = new javax.swing.JButton();
        btnLoadCharacter = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Z003", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(180, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vampyre The Maquerade ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 100));

        jLabel2.setFont(new java.awt.Font("Z003", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Character genetor ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, 60));

        btnNewCharacter.setBackground(new java.awt.Color(180, 0, 0));
        btnNewCharacter.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        btnNewCharacter.setText("New Character ");
        btnNewCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCharacterActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, 50));

        btnLoadCharacter.setBackground(new java.awt.Color(180, 0, 0));
        btnLoadCharacter.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        btnLoadCharacter.setText("Load Character ");
        btnLoadCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCharacterActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoadCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 190, 50));

        btnInstructions.setBackground(new java.awt.Color(180, 0, 0));
        btnInstructions.setFont(new java.awt.Font("Z003", 1, 18)); // NOI18N
        btnInstructions.setText("Instructions");
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });
        jPanel1.add(btnInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 190, 50));

        backgroundImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCharacterActionPerformed
        CreateCharacter1 createCharacter1 = new CreateCharacter1(this, true);
        createCharacter1.setVisible(true);
    }//GEN-LAST:event_btnNewCharacterActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        Instructions instructions = new Instructions(this, true);
        instructions.setVisible(true);
    }//GEN-LAST:event_btnInstructionsActionPerformed

    private void btnLoadCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCharacterActionPerformed
        SavedSheets savedSheets = new SavedSheets(this, true);
        savedSheets.setVisible(true);
    }//GEN-LAST:event_btnLoadCharacterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnLoadCharacter;
    private javax.swing.JButton btnNewCharacter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
