/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.Charac;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logic.Logic;

/**
 *
 * @author sinsentido
 */
public class SavedSheets extends javax.swing.JDialog {
    private MainScreen mainScreen;
    /**
     * Creates new form SavedSheets
     */
    public SavedSheets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mainScreen = (MainScreen)parent;
        initTable();
    }
    
    private void initTable(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        //Set the name of the columns
        dtm.setColumnIdentifiers(new String[]{
            "Character name", "Player name", "Chronicle"
        });
        
        tblSavedSheets.setModel(dtm);
        loadSavedFiles(Logic.readSavedFiles());
    }
    
    public void loadSavedFiles(List<Charac> characters){
        DefaultTableModel dtm = (DefaultTableModel)tblSavedSheets.getModel();
        String[] tableInfo = new String[3];
                    
        for(int i=0; i<characters.size(); i++){
            tableInfo[0] = characters.get(i).getCharName();
            tableInfo[1] = characters.get(i).getPlayer();
            tableInfo[2] = characters.get(i).getChronicle();
            dtm.addRow(tableInfo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSavedSheets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSavedSheets = new javax.swing.JTable();
        btnOpen = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSavedSheets.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblSavedSheets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavedSheets.setText("Saved character sheets");

        tblSavedSheets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSavedSheets);

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSavedSheets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSavedSheets, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        CharSheet charSheet = new CharSheet(mainScreen, true);
        DefaultTableModel dtm = (DefaultTableModel)tblSavedSheets.getModel();
        String filename = "";
        
        if(tblSavedSheets.getSelectedRow() != -1){
            filename += tblSavedSheets.getValueAt(tblSavedSheets.getSelectedRow(), 0).toString();
            filename += tblSavedSheets.getValueAt(tblSavedSheets.getSelectedRow(), 1).toString();
            filename += tblSavedSheets.getValueAt(tblSavedSheets.getSelectedRow(), 2).toString();
            
            filename = filename.replaceAll(" ", "");
            
            charSheet.printCharacValues(Logic.buildCharacFromFile(Logic.lookForCharacFile(filename)));
            charSheet.setVisible(true);
        }

        
    }//GEN-LAST:event_btnOpenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSavedSheets;
    private javax.swing.JTable tblSavedSheets;
    // End of variables declaration//GEN-END:variables
}
